language: go

go:
  - 1.6
  - 1.7
  - 1.8

env:
  matrix:
    - GOOS=linux
    - GOOS=darwin
    - GOOS=freebsd
    - GOOS=windows

script:
  - go build && go test ./...

notifications:
  email: false
